import { createContext, useContext, useState, useEffect, useMemo, useCallback, ReactNode } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

type Language = 'ko' | 'en';

const translations = {
  ko: {
    greeting: "안녕하세요",
    greetingSub: "오늘 복용 상태를 확인해보세요",
    todayProgress: "오늘의 진행 상황",
    dosesTaken: "회 복용 완료",
    allDoneToday: "오늘 모든 약을 복용했어요!",
    noMedsYet: "등록된 약이 없어요",
    addFirstMed: "약을 등록하고 복용을 관리해 보세요",
    addMedication: "약 추가",
    noScheduleToday: "오늘 복용 예정인 약이 없어요",
    done: "완료",
    today: "오늘",
    medications: "내 약",
    history: "기록",
    myMedications: "내 약 목록",
    noMedsAdded: "등록된 약이 없어요",
    tapToAdd: "+ 버튼을 눌러 약을 등록하세요",
    deleteMedication: "약 삭제",
    deleteConfirm: "을(를) 삭제하시겠어요? 복용 기록도 함께 삭제됩니다.",
    cancel: "취소",
    delete: "삭제",
    daily: "일 복용",
    addMedicationTitle: "약 추가하기",
    editMedicationTitle: "약 수정하기",
    updateMedication: "수정하기",
    medName: "약 이름",
    medNamePlaceholder: "예) 비타민 D, 오메가-3...",
    color: "색상",
    whenToTake: "복용 시간",
    selectAll: "해당하는 시간을 모두 선택하세요",
    morning: "아침",
    noon: "점심",
    afternoon: "오후",
    evening: "저녁",
    night: "밤",
    timesPerDay: "회/일",
    saveMedication: "저장하기",
    nameRequired: "이름을 입력해주세요",
    nameRequiredMsg: "약 이름을 입력해주세요.",
    scheduleRequired: "복용 시간을 선택해주세요",
    scheduleRequiredMsg: "최소 한 개의 복용 시간을 선택해주세요.",
    unitRequired: "단위를 입력해주세요",
    unitRequiredMsg: "직접 입력 단위를 입력해주세요.",
    confirmDose: "복용 확인",
    takePhotoOf: "약 사진을 찍어주세요",
    retake: "다시 찍기",
    markAsTaken: "복용 완료",
    saving: "저장 중...",
    cameraAccess: "카메라 접근 필요",
    cameraAccessMsg: "복용 인증을 위해 약 사진을 찍을 수 있도록 카메라 접근을 허용해주세요.",
    allowCamera: "카메라 허용",
    orPickGallery: "또는 갤러리에서 선택",
    loadingCamera: "카메라 로딩 중...",
    error: "오류",
    failedTakePhoto: "사진 촬영에 실패했어요. 다시 시도해주세요.",
    failedSave: "저장에 실패했어요. 다시 시도해주세요.",
    thisWeek: "이번 주",
    dayStreak: "연속 복용",
    thisWeekLabel: "이번 주",
    thisMonth: "이번 달",
    summary: "요약",
    totalDoses: "총 복용",
    photos: "사진",
    noDataYet: "데이터가 없어요",
    addMedsToSee: "약을 등록하고 복용하면 통계를 확인할 수 있어요",
    language: "언어",
    korean: "한국어",
    english: "English",
    settings: "설정",
    customTime: "직접 입력",
    mealTiming: "식사 기준",
    beforeMeal: "식전",
    duringMeal: "식중",
    afterMeal: "식후",
    breakfast: "아침",
    lunch: "점심",
    dinner: "저녁",
    dosage: "복용량",
    dosagePlaceholder: "예) 1",
    tablet: "정",
    customUnit: "기타",
    customUnitPlaceholder: "단위 입력 (예: g, ml, 방울)",
    dosageUnit: "단위",
    presetTimes: "시간 선택",
    orCustomTime: "직접 시간 입력",
    hour: "시",
    minute: "분",
    add: "추가",
    selectedTimes: "선택된 시간",
    amount: "용량",
    memo: "메모",
    memoPlaceholder: "복용 관련 메모를 적어주세요",
    wakeUp: "기상 직후",
    beforeBed: "자기 전",
    anytime: "아무때나",
    monthlyCalendar: "복용 달력",
    allMeds: "전체",
    allTaken: "모두 복용",
    partiallyTaken: "일부 복용",
    notTaken: "미복용",
    noDoses: "복용 기록 없음",
    of: "/",
    sun: "일",
    mon: "월",
    tue: "화",
    wed: "수",
    thu: "목",
    fri: "금",
    sat: "토",
    back: "뒤로",
    photoArchive: "복용 사진",
    noPhotosYet: "사진이 없어요",
    morningBlock: "아침",
    afternoonBlock: "오후",
    eveningBlock: "저녁",
    bedtimeBlock: "취침 전",
    statusPending: "미복용",
    statusTaken: "복용 완료",
    statusOverdue: "지연됨",
    statusDuplicate: "중복 위험",
    tapToTake: "탭하여 복용 기록",
    undoAction: "취소",
    doseTaken: "복용이 기록되었어요",
    duplicateWarning: "중복 복용 경고",
    duplicateMessage: "이 약은 이미 복용한 것으로 기록되어 있어요.",
    duplicateOverride: "그래도 기록하기",
    lastTaken: "마지막 복용",
    justNow: "방금 전",
    minutesAgo: "분 전",
    hoursAgo: "시간 전",
    todayAt: "오늘",
    caregiverView: "가족 요약",
    caregiverTitle: "복용 현황",
    caregiverCompleted: "복용 완료",
    caregiverPending: "대기 중",
    caregiverMissed: "미복용",
    caregiverAllDone: "오늘 모든 약을 잘 복용했어요!",
    caregiverSomePending: "아직 복용하지 않은 약이 있어요",
    caregiverSomeMissed: "놓친 복용이 있어요",
    blockCompleted: "완료",
    noMedsRegistered: "등록된 약이 없어요",
    addMedsToStart: "약을 등록하면 복용 현황을 확인할 수 있어요",
    overallProgress: "전체 진행률",
    login: "로그인",
    register: "회원가입",
    username: "아이디",
    password: "비밀번호",
    displayNameLabel: "이름",
    usernamePlaceholder: "아이디를 입력하세요",
    passwordPlaceholder: "비밀번호를 입력하세요",
    displayNamePlaceholder: "표시될 이름을 입력하세요",
    noAccount: "계정이 없으신가요?",
    hasAccount: "이미 계정이 있으신가요?",
    loginFailed: "로그인에 실패했어요",
    registerFailed: "회원가입에 실패했어요",
    allFieldsRequired: "모든 항목을 입력해주세요",
    shareWithFamily: "가족과 공유하기",
    generateInvite: "초대 코드 만들기",
    inviteCode: "초대 코드",
    inviteCodeDesc: "이 코드를 가족에게 보내주세요",
    enterInviteCode: "초대 코드 입력",
    enterCodePlaceholder: "6자리 코드를 입력하세요",
    acceptInvite: "연결하기",
    invalidCode: "유효하지 않은 코드에요",
    codeExpired: "만료된 코드에요",
    codeUsed: "이미 사용된 코드에요",
    connected: "연결됨",
    pendingConnection: "대기 중",
    disconnect: "연결 해제",
    disconnectConfirm: "연결을 해제하시겠어요?",
    myConnections: "연결된 사람들",
    noConnections: "연결된 가족이 없어요",
    connectToStart: "초대 코드를 입력하거나 공유해서 가족과 연결하세요",
    nickname: "별명",
    nicknamePlaceholder: "예) 엄마, 아빠, 할머니",
    viewStatus: "복용 현황 보기",
    sendNudge: "응원 보내기",
    nudgeSent: "응원을 보냈어요!",
    timeMeds: "약 드실 시간이에요",
    greatJob: "오늘도 잘 하셨어요",
    allDoneSuccess: "오늘 약을 모두 잘 챙겨 드셨습니다 👍",
    notTakenYet: "아직 복용하지 않았습니다",
    missedRecovery: "복용 시간이 지났습니다 (지금 복용 가능)",
    logout: "로그아웃",
    profile: "프로필",
    timezone: "시간대",
    copyCode: "코드 복사",
    codeCopied: "복사되었어요!",
    expiresIn: "7일 후 만료",
    connectionSuccess: "연결되었어요!",
    bulkCheckIn: "모두 복용 완료",
    bulkCheckInConfirm: "이 시간대의 약을 모두 복용하셨나요?",
    confirm: "확인",
    takeNow: "복용 완료 ✔️",
    alreadyTaken: "이미 복용했습니다",
    takeLater: "나중에 복용 예정",
    takeNowAction: "지금 복용하세요",
    nudgeSentTo: "에게 보냄",
    nudgeReceivedFrom: "이(가) 보냈습니다",
    completedOf: "완료",
    dailySummary: "오늘의 복용",
    remainingMeds: "남은 약",
    timeBlockDefault: "시간대 선택",
    exactTimeToggle: "정확한 시간 설정",
    duplicateAlreadyTaken: "이미 오늘 복용한 약입니다",
  },
  en: {
    greeting: "Hello",
    greetingSub: "Check your medication status today",
    todayProgress: "Today's Progress",
    dosesTaken: "doses taken",
    allDoneToday: "All done for today!",
    noMedsYet: "No medications yet",
    addFirstMed: "Add your first medication to start tracking",
    addMedication: "Add Medication",
    noScheduleToday: "No medications scheduled today",
    done: "Done",
    today: "Today",
    medications: "Medications",
    history: "History",
    myMedications: "My Medications",
    noMedsAdded: "No medications added",
    tapToAdd: "Tap the + button to add your first medication",
    deleteMedication: "Delete Medication",
    deleteConfirm: "? All dose records will also be deleted.",
    cancel: "Cancel",
    delete: "Delete",
    daily: "x daily",
    addMedicationTitle: "Add Medication",
    editMedicationTitle: "Edit Medication",
    updateMedication: "Update",
    medName: "Medication Name",
    medNamePlaceholder: "e.g., Vitamin D, Omega-3...",
    color: "Color",
    whenToTake: "When to take",
    selectAll: "Select all that apply",
    morning: "Morning",
    noon: "Noon",
    afternoon: "Afternoon",
    evening: "Evening",
    night: "Night",
    timesPerDay: "time(s)/day",
    saveMedication: "Save Medication",
    nameRequired: "Name Required",
    nameRequiredMsg: "Please enter a medication name.",
    scheduleRequired: "Schedule Required",
    scheduleRequiredMsg: "Please select at least one time.",
    unitRequired: "Unit Required",
    unitRequiredMsg: "Please enter a custom unit name.",
    confirmDose: "Confirm Dose",
    takePhotoOf: "Take a photo of your medication",
    retake: "Retake",
    markAsTaken: "Mark as Taken",
    saving: "Saving...",
    cameraAccess: "Camera Access Needed",
    cameraAccessMsg: "To verify your dose, we need access to your camera to take a photo of your medication.",
    allowCamera: "Allow Camera Access",
    orPickGallery: "Or pick from gallery",
    loadingCamera: "Loading camera...",
    error: "Error",
    failedTakePhoto: "Failed to take photo. Please try again.",
    failedSave: "Failed to save. Please try again.",
    thisWeek: "This Week",
    dayStreak: "Day Streak",
    thisWeekLabel: "This Week",
    thisMonth: "This Month",
    summary: "Summary",
    totalDoses: "Total Doses",
    photos: "Photos",
    noDataYet: "No data yet",
    addMedsToSee: "Add medications and start tracking to see your stats",
    language: "Language",
    korean: "한국어",
    english: "English",
    settings: "Settings",
    customTime: "Custom Time",
    mealTiming: "Meal Timing",
    beforeMeal: "Before Meal",
    duringMeal: "During Meal",
    afterMeal: "After Meal",
    breakfast: "Breakfast",
    lunch: "Lunch",
    dinner: "Dinner",
    dosage: "Dosage",
    dosagePlaceholder: "e.g., 1",
    tablet: "tablet",
    customUnit: "Custom",
    customUnitPlaceholder: "Enter unit (e.g., g, ml, drops)",
    dosageUnit: "Unit",
    presetTimes: "Preset Times",
    orCustomTime: "Enter custom time",
    hour: "Hour",
    minute: "Min",
    add: "Add",
    selectedTimes: "Selected Times",
    amount: "Amount",
    memo: "Memo",
    memoPlaceholder: "Add notes about this medication",
    wakeUp: "Wake up",
    beforeBed: "Bedtime",
    anytime: "Anytime",
    monthlyCalendar: "Calendar",
    allMeds: "All",
    allTaken: "All taken",
    partiallyTaken: "Partial",
    notTaken: "Not taken",
    noDoses: "No doses recorded",
    of: "/",
    sun: "Sun",
    mon: "Mon",
    tue: "Tue",
    wed: "Wed",
    thu: "Thu",
    fri: "Fri",
    sat: "Sat",
    back: "Back",
    photoArchive: "Dose Photos",
    noPhotosYet: "No photos yet",
    morningBlock: "Morning",
    afternoonBlock: "Afternoon",
    eveningBlock: "Evening",
    bedtimeBlock: "Bedtime",
    statusPending: "Not taken",
    statusTaken: "Taken",
    statusOverdue: "Overdue",
    statusDuplicate: "Duplicate risk",
    tapToTake: "Tap to mark as taken",
    undoAction: "Undo",
    doseTaken: "Dose recorded",
    duplicateWarning: "Duplicate Dose Warning",
    duplicateMessage: "You already marked this medication as taken.",
    duplicateOverride: "Record anyway",
    lastTaken: "Last taken",
    justNow: "just now",
    minutesAgo: "min ago",
    hoursAgo: "hr ago",
    todayAt: "Today",
    caregiverView: "Family",
    caregiverTitle: "Medication Status",
    caregiverCompleted: "Completed",
    caregiverPending: "Pending",
    caregiverMissed: "Missed",
    caregiverAllDone: "All medications taken today!",
    caregiverSomePending: "Some medications still pending",
    caregiverSomeMissed: "Some doses were missed",
    blockCompleted: "Done",
    noMedsRegistered: "No medications registered",
    addMedsToStart: "Add medications to see status",
    overallProgress: "Overall Progress",
    login: "Log In",
    register: "Sign Up",
    username: "Username",
    password: "Password",
    displayNameLabel: "Display Name",
    usernamePlaceholder: "Enter your username",
    passwordPlaceholder: "Enter your password",
    displayNamePlaceholder: "Enter your display name",
    noAccount: "Don't have an account?",
    hasAccount: "Already have an account?",
    loginFailed: "Login failed",
    registerFailed: "Registration failed",
    allFieldsRequired: "All fields are required",
    shareWithFamily: "Share with Family",
    generateInvite: "Generate Invite Code",
    inviteCode: "Invite Code",
    inviteCodeDesc: "Share this code with your family",
    enterInviteCode: "Enter Invite Code",
    enterCodePlaceholder: "Enter 6-digit code",
    acceptInvite: "Connect",
    invalidCode: "Invalid code",
    codeExpired: "Code expired",
    codeUsed: "Code already used",
    connected: "Connected",
    pendingConnection: "Pending",
    disconnect: "Disconnect",
    disconnectConfirm: "Are you sure you want to disconnect?",
    myConnections: "My Connections",
    noConnections: "No family connections yet",
    connectToStart: "Enter or share an invite code to connect with family",
    nickname: "Nickname",
    nicknamePlaceholder: "e.g., Mom, Dad, Grandma",
    viewStatus: "View Status",
    sendNudge: "Send Encouragement",
    nudgeSent: "Encouragement sent!",
    timeMeds: "Time for your meds",
    greatJob: "Great job today",
    allDoneSuccess: "All medications completed for today! Great job! 👍",
    notTakenYet: "Not taken yet",
    missedRecovery: "Overdue (you can still take it now)",
    logout: "Log Out",
    profile: "Profile",
    timezone: "Timezone",
    copyCode: "Copy Code",
    codeCopied: "Copied!",
    expiresIn: "Expires in 7 days",
    connectionSuccess: "Connected!",
    bulkCheckIn: "Take all",
    bulkCheckInConfirm: "Did you take all medications for this time block?",
    confirm: "Confirm",
    takeNow: "Take Now ✔️",
    alreadyTaken: "Already taken",
    takeLater: "Scheduled for later",
    takeNowAction: "Take now",
    nudgeSentTo: "Sent to ",
    nudgeReceivedFrom: " sent you",
    completedOf: "completed",
    dailySummary: "Today's Medications",
    remainingMeds: "remaining",
    timeBlockDefault: "Select time block",
    exactTimeToggle: "Set exact time",
    duplicateAlreadyTaken: "Already taken today",
  },
} as const;

type TranslationKey = keyof typeof translations.ko;

interface LanguageContextValue {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

const LANGUAGE_KEY = '@pillmate_language';

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('ko');
  const [loaded, setLoaded] = useState(false);

  useEffect(() => {
    AsyncStorage.getItem(LANGUAGE_KEY).then(val => {
      if (val === 'en' || val === 'ko') setLanguageState(val);
      setLoaded(true);
    });
  }, []);

  const setLanguage = useCallback(async (lang: Language) => {
    setLanguageState(lang);
    await AsyncStorage.setItem(LANGUAGE_KEY, lang);
  }, []);

  const t = useCallback((key: TranslationKey): string => {
    return translations[language][key] || key;
  }, [language]);

  const value = useMemo(() => ({ language, setLanguage, t }), [language, setLanguage, t]);

  if (!loaded) return null;

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
